targets = EXE1 EXE18 EXE26 EXE27

EXE1: ./TwoSum/E1.cpp
	g++ -std=c++11 -g -o EXE1 ./TwoSum/E1.cpp	

EXM18: ./4Sum/M18.cpp
	g++ -std=c++11 -g -o EXM18 ./4Sum/M18.cpp

EXE26: ./RemoveDuplicatesFromSortedArray/E26.cpp
	g++ -std=c++11 -g -o EXE26  ./RemoveDuplicatesFromSortedArray/E26.cpp

EXE27: ./RemoveElement/E27.cpp
	g++ -std=c++11 -g -o EXE27 ./RemoveElement/E27.cpp


.PHONY: clean
clean:
	rm -r *.dSYM
	rm EX* 
	
